### ISSUE TITLE
DRAT file copy script misses all sorts of file naming issues

### ISSUE THREAD

**Issue by chrismattmann** [apache/drat#94]
We really need a better solution than the file copy used by the RAT audit tool. Undeniably, it's very interesting that we have a great sed command and so forth to handle files, but we need to support all sorts of files, with '$' in the name; with ' ' whitespace, etc. #93 exposed this issue.

**Comment by karanjeets** [comment]
As suggested by @chrismattmann, we can do as follows in order to reach a better solution:

(a) Remove the copy part from the CAS-PGE generated bash script.
(b) Use CAS-PGE file staging to natively copy the input files but for this, we will need a custom Data Transferrer for DRAT which can keep the file names unique.

**Comment by chrismattmann** [comment]
this is now fixed RE: #93
